[package]
name = "bibadd"
version = "0.1.0"
edition = "2021"

[dependencies]
biblatex = "0.4.2"
clap = "2.34.0"
eyre = "0.6.5"
glob = "0.3.0"
log = "0.4.14"
reqwest = { version = "0.11", features = ["blocking"] }
stderrlog = "0.5.1"

[dev-dependencies]
assert_cmd = "2.0.2"
assert_fs = "1.0.6"
predicates = "2.1.0"
